export interface Course {
    class_id : number,
    course_code : string,
    course_name_eng : string,
    course_name : string,
    section : number,
    study_code : string,
    faculty_id : number,
    facultyname : string,
    acadyear : number,
    semester : number,
    totalseat : number,
    enrollseat : number,
    sequence : number,
    weekday : number,
    time1text : string,
    time1of : string,
    time2text : string,
    time2of : string,
    week_call : string,
    week_call_abb : string,
    week_call_thai : string,
    room_code : string | null,
    room_name : string | null,
    building_code : string | null,
    capacity : string | null
}